receiving_refactoring
umbrellio/table_sync pull request #36
Opened 2020-10-05 11:46 UTC by 7dr1v3

2020-10-06 12:12 UTC, VegetableProphet commented on .rubocop.yml
> +  Enabled: false
Newline

2020-10-16 16:25 UTC, loadkpi requested changes

2020-10-16 16:25 UTC, loadkpi commented on CHANGELOG.md
> +### Changed
и про нэйминг TableSync::Publisher, TableSync::BatchPublisher ..

2020-10-16 16:25 UTC, loadkpi commented on CHANGELOG.md
> +### Changed
и про raw_data/data, current_row/row

2020-10-16 16:25 UTC, loadkpi commented on CHANGELOG.md
> +### Changed
вообще было бы круто добавить хау-то апдейт то 3.0, потому что очень много чего поменяно по нэймингам

2020-10-19 08:17 UTC, VegetableProphet commented on lib/table_sync/utils/interface_checker.rb
> +__END__
А нам только из-за этого одного места надо селф_дату подключать. Это прям надо?

2020-10-19 12:30 UTC, loadkpi requested changes

2020-10-19 12:30 UTC, loadkpi commented on lib/table_sync.rb
> +      @orm = val
а этот теперь `@orm` вообще где-то используется? кажется, что нет

2020-10-19 12:30 UTC, loadkpi commented on lib/table_sync/errors.rb
> +  class DataError < Error
а есть какой-то резон, почему мы решили объединить UnprovidedEventTargetKeysError и ошибку по дубликатам строк в одну?

2020-10-19 12:30 UTC, loadkpi commented on lib/table_sync/receiving/handler.rb
> +      row.merge!(config.additional_data(row: row))
теперь, получается, `row:` в dsl-методах зависит от предшествующих методов.
то есть раньше можно было написать
```
mapping_overrides {old_id: :new_id}
additional_data do |row:|
 { id: 2 * row[:old_id] }
```
т.к. использовалась`original_row_for_data`
а теперь будет ошибка и это не особо очевидно, почему `row:` разное

2020-10-19 12:30 UTC, loadkpi commented on lib/table_sync/receiving/handler.rb
> +          config.after_commit_on_update(**params.merge(results: results))
указали ли мы в доке, что after_commit_on_update/after_commit_on_destroy выполняется только при реальном изменении данных?

2020-10-19 12:30 UTC, loadkpi commented on lib/table_sync/receiving/handler.rb
> +    configs.each do |config|
почему решили убрать проверку на `TableSync::UndefinedConfig` ?

2020-10-19 12:30 UTC, loadkpi commented on lib/table_sync/receiving/model/active_record.rb
> +      sanitized_data = data.map { |attr| attr.select { |key, _value| target_keys.include?(key) } }
я правильно понимаю, что в `sanitized_data` может оказаться что-то типа: `[{},{}]` ?

2020-10-19 12:30 UTC, loadkpi commented on lib/table_sync/receiving/model/active_record.rb
> +          query = raw_model.lock("FOR UPDATE").where(row)
если не ошибаюсь, `where({})` в ActiveRecord не вызовет ошибку, а просто сделает `select * from raw_table`

2020-10-19 12:30 UTC, loadkpi commented on lib/table_sync/receiving/model/sequel.rb
> -      data = Array.wrap(data)
упустил момент, почему мы уверены, что тут всегда массив теперь?

2020-10-19 12:30 UTC, loadkpi commented on lib/table_sync/errors.rb
> +      super "data: #{data.inspect}, target_keys: #{target_keys.inspect}, result: #{result.inspect}"
в этом файле мы в каких-то местах используем `super("")`, в других - `super ""`

2020-10-19 12:30 UTC, loadkpi commented on lib/table_sync.rb
> +    attr_reader :publishing_adapter
не хотим все добавленные штуки покрыть пометкой `@since` ?

2020-10-19 14:34 UTC, 7dr1v3 commented on CHANGELOG.md
> +### Changed
howto не хочу добавлять, предлагаю ограничиться чендж логом и докой, не такой уж и публичный у нас этот гем.

2020-10-19 14:40 UTC, 7dr1v3 commented on docs/receiving.md
> +`default_values` defined only for `:update` event
вообще лишняя строка

2020-10-19 15:13 UTC, 7dr1v3 commented on lib/table_sync.rb
> +      @orm = val
не известно используется он где то или нет, просто для совместимости оставил, я тут по минимуму изменил, только необходимое для разделения на модули. В идеале неплохо бы вообще вынести модели и адаптеры в отдельные гемы, но не в этот раз.

2020-10-19 15:13 UTC, 7dr1v3 commented on lib/table_sync/errors.rb
> -  class UndefinedConfig < Error
я вообще не вижу смысла в проверке наличия хендлера, какой от него толк? сам по себе он пропасть не может, если будет ошибка то она будет выявлена при тестировании, тупо данных не будет в базе, такое сложно пропустить.
Все что он делает это срет ошибками если сделать роуты в реббите до выката хендлера.

2020-10-19 15:13 UTC, 7dr1v3 commented on lib/table_sync/errors.rb
> +  class DataError < Error
Предположил что ошибок связанных с валидацией даты может быть больше и сделал общий кейс с возможностью передать дескрипшен.

2020-10-19 15:15 UTC, 7dr1v3 commented on lib/table_sync/errors.rb
>      # @param target_attributes [Hash<Symbol|String,Any>]
удалил

2020-10-19 15:16 UTC, 7dr1v3 commented on lib/table_sync/errors.rb
>      # @param target_attributes [Hash<Symbol|String,Any>]
удалил

2020-10-19 15:36 UTC, 7dr1v3 commented on lib/table_sync/receiving/config.rb
> +      unless @events.all?(&[:update, :destroy].method(:include?))
сделал TableSync::Receiving::AVAILABLE_EVENTS

2020-10-19 15:40 UTC, 7dr1v3 commented on lib/table_sync/receiving/config.rb
> +      # In a configs this options is requested as it is
множественное

2020-10-19 15:50 UTC, 7dr1v3 commented on lib/table_sync/receiving/handler.rb
> +    configs.each do |config|
выше отписался, на мой взгляд она не имеет практического смысла.

2020-10-19 15:50 UTC, 7dr1v3 commented on lib/table_sync/receiving/handler.rb
> +      row.merge!(config.additional_data(row: row))
Мне кажется раньше было менее очевидно, изменения в любом случае применяются к некой текущей row но строятся на основе оригинальной row. Сейчас изменения применяются именно к тому что передается в параметрах. В крайнем случае всегда доступна raw_data

2020-10-19 16:12 UTC, 7dr1v3 commented on lib/table_sync/receiving/model/active_record.rb
> -    def upsert(data:, target_keys:, version_key:, first_sync_time_key:, default_values:)
его добавили потому что не разобрались в доке тейбл синка, то что он делает реализуется через default_values

2020-10-19 16:12 UTC, 7dr1v3 commented on lib/table_sync/receiving/model/active_record.rb
> +      sanitized_data = data.map { |attr| attr.select { |key, _value| target_keys.include?(key) } }
походу нужно писать спек на этот кейс

2020-10-19 16:12 UTC, 7dr1v3 commented on lib/table_sync/receiving/model/sequel.rb
> -      data = Array.wrap(data)
потому что в TableSync::Receiving::Handler 
```
  def data=(data)
    super(Array.wrap(data[:attributes]))
  end

```

для ресивера больше нету разницы между батчами и не батчами.

2020-10-19 16:12 UTC, 7dr1v3 commented on lib/table_sync/utils/interface_checker.rb
> +__END__
Мне кажется этот класс вообще можно вынести в отдельный гем и юзать в наших гемах, если вам зайдет его концепция. А так, тейбл синк рельсу требует для своей работы, а ты до бедной селф даты докапался)

2020-10-20 12:50 UTC, VegetableProphet commented on lib/table_sync/errors.rb
> -  class UndefinedConfig < Error
Так а в чём проблема, что он ошибку кидает? Довольно полезно вроде. Хотя бы понятно, что происходит.
А так он будет внутри rabbit_messaging падать при поиске хэндлера со, скорее всего, непонятной для непосвящённого ошибкой.

2020-10-20 12:50 UTC, VegetableProphet commented on lib/table_sync/receiving/model/active_record.rb
> -    def upsert(data:, target_keys:, version_key:, first_sync_time_key:, default_values:)
Ну надо тогда как-то подробнее это описать и пингануть ребят, которые этим пользуются. А то им сюрприз будет.

2020-10-20 12:50 UTC, VegetableProphet commented on lib/table_sync/utils/interface_checker.rb
> +__END__
Ну блин. Зачем добавлять лишние зависимости, только потому что уже какие-то зависимости существуют?
Звучит странно.

2020-10-20 16:32 UTC, 7dr1v3 commented on lib/table_sync/errors.rb
> -  class UndefinedConfig < Error
Он не будет падать в реббит месседжинг. просто сообщения будут уходить в никуда.
Эта ошибка кидалась в случае когда в реббите роуты прописаны но ревизия с новым хендлером еще не выкачена. Мне просто непонятно от чего она спасает, от какой ситуации? Когда чел напишет новый хендлер, протестирует на стейдже что данные приходят, потом ебнется головой, удалит хендлер, выкатит ревизию на прод без хендлера, пропишет роуты в реббите прода и не проверив синкаются ли данные просто закроет таску и забудет про нее?

2020-10-20 16:35 UTC, 7dr1v3 commented on lib/table_sync/receiving/model/active_record.rb
> -    def upsert(data:, target_keys:, version_key:, first_sync_time_key:, default_values:)
этим пользовались в хиппо в кассе, там я переписал на default_values и юра в курсе этого рофла. в ченджлоге написано какие опции удалены, она не единственная еще on_destroy и partitions

2020-10-20 16:37 UTC, 7dr1v3 commented on lib/table_sync/utils/interface_checker.rb
> +__END__
почему она лишняя?  там ямл на 50 строчек

2020-10-20 17:05 UTC, 7dr1v3 commented on lib/table_sync/receiving/model/active_record.rb
> +          query = raw_model.lock("FOR UPDATE").where(row)
↑

2020-10-20 21:43 UTC, loadkpi commented on lib/table_sync.rb
> +      @orm = val
я бы предложил выпилить... указав в чэйнджлоге что в место orm теперь publishing_adapter и receiving_model. он как-то крипово выглядит и в геме не юзается, раз уж мы тут брейкинг чейнджес делаем, то можно и это заоодно.

2020-10-20 21:45 UTC, loadkpi commented on lib/table_sync/receiving/handler.rb
> +          config.after_commit_on_update(**params.merge(results: results))
вот я тоже склонен к тому, чтобы вызывать ее в любом случае. а дальше пусть сам разработчик разбирается.

2020-10-20 21:47 UTC, loadkpi commented on lib/table_sync.rb
> +    attr_reader :publishing_adapter
ну вообще да, удобнее ориентироваться в изменяемых апихах.. по крайней мере мы его юзаем уже здесь, так что или отказываться, или поддерживать. я за второе.

2020-10-21 06:55 UTC, 0exp commented on docs/receiving.md
> +```
ruby

2020-10-21 06:55 UTC, 0exp commented on docs/receiving.md
> +```
ruby

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync.rb
> +        raise ORMNotSupported.new(val.inspect)
в неймингах оишбок по конвеншнам надо дописывать `Error` на конце, а то по имени кажется что это просто класс-функция, а не эксепшн :\

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/config.rb
> +      # config.option { ... } - set proc as value
`as computed value`

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/config.rb
> +    def allow_event?(name)
`allowed`

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/config.rb
> +      events.include?(name)
а если пустой масисв эвентов будет? 🤔

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/config.rb
> +# rubocop:enable Layout/ArgumentAlignment
какой-то супер-переусложненный конфиг. можно проще напсать, но похоже снова не в этот раз ((

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/config.rb
> +      @events = [events].flatten.map(&:to_sym)
а зачем тут flatten?

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/config_decorator.rb
> +    # rubocop:disable Metrics/ParameterLists
`Metrics/ParameterLists` стоит вырубить прямо в .rubocop.yml

для фреймворк-гемов и инфраструктурного кода этот коп вообще безсмысленен (он для бизнес-логики больше)

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/dsl.rb
> +      self
а зачем тут self возвращать? мы цепочку вызовов `receive` вроде не делаем

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/handler.rb
> +      next if target_keys.all?(&row.keys.method(:include?))
тут жесткий просед по перфу будет, если мы на кажду итерацию метод-обэжекты с инстансов вычленять будем и трансформить в проки

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/handler.rb
> +    if data.uniq { |row| row.slice(*target_keys) }.size != data.size
тут на все строки в data создастся хэшей и массивов по количеству rows*3, и иногда это дохрена получается :feelsgood: может просто проитерируем и упадем на первом несовпадении?

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/handler.rb
> +      else
может разобьем на 2 метода (update и destroy), и свитч-кейсом будем перебирать, а то я вижу что как бы что для всех не-update-событий мы делаем destroy 🤔 чтобы ни пришло

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/handler.rb
> +        return if results.empty?
а почему сразу выходим, после коммита не было изменений? хуки бы хотелось выполнить тоже 🤔

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/model/active_record.rb
> +        if row.to_a.size > 1
на все апсерты тут опять +1 массив создается :feelsgood: может без to_a сможем зачекать инвалидацию апсерта?

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/model/active_record.rb
> +      result = query.destroy_all.map(&method(:row_to_hash))
- зачем `&method`? это дорогая операция. дешевле явно прок объявить и внутри вызывать row_to_hash
- а тут можно без создания нового массива проверить `result.size > data.size`?

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/model/active_record.rb
> +      sanitized_data.each.with_index do |row, index|
промежуточный enumerator от each не нужен. each_with_index сразу можно

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/receiving/model/active_record.rb
> +      sanitized_data = data.map { |attr| attr.select { |key, _value| target_keys.include?(key) } }
а точно до сюда доедет `[{}, {}]`? где-то до вызова этого destroy мы должны упасть на анпровайдед таргет кейс вроде как 🤔  (еще на этапе ресивинга)

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/utils/interface_checker.rb
> +    self
а зачем селф возвращать?

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/utils/proc_keywords_resolver.rb
> +# ¯\_(ツ)_/¯
1. этот кейс тоже нормальный
2. для такого нужно объявлять прок в виде `proc { |first:, **| }`

2020-10-21 06:55 UTC, 0exp commented on lib/table_sync/utils/proc_keywords_resolver.rb
> +      proc_for_wrap.call(**keywords.slice(*available_keywords), &block)
зачем эта магия?)

2020-10-21 07:00 UTC, 0exp commented on README.md
> +- [Messages protocol](docs/messages_protocol.md)
`Message`

2020-10-21 07:18 UTC, 0exp commented on docs/messages_protocol.md
> +
если дока на протокол - давай тут каждое поле и опишем тоже

2020-10-21 07:18 UTC, 0exp commented on lib/table_sync/receiving/config.rb
> +      return true if events.nil?
надо бы в доку добавить, что можно явно nil передать - и это будет пониматься что все события allowed

2020-10-21 07:18 UTC, 0exp commented on lib/table_sync/receiving/model/sequel.rb
> +      result = dataset.returning.where(::Sequel.|(*sanitized_data)).delete
зачем здесь sanitized_data, если ты можешь сразу по target_keys удалять?

2020-10-21 07:20 UTC, 0exp commented on lib/table_sync/receiving/model/sequel.rb
> +      result = dataset.returning.where(::Sequel.|(*sanitized_data)).delete
а не. тут же select. не то сказал)

2020-10-21 07:49 UTC, 0exp commented on lib/table_sync/utils/interface_checker.rb
> +class TableSync::Utils::InterfaceChecker
а зачем эта штука понадобилась? это для кастомных моделей, чтобы на этапе формирования ресиверов сразу падать, а не в рантайме (когда аппликуха уже работает)? если так - то стоит явно описать это в доке к классу тут тоже, т.к. тут какое-то пространное описание про поведение руби.

2020-10-21 12:34 UTC, 7dr1v3 commented on lib/table_sync.rb
> +      @orm = val
тогда потеряется способ одной командой выбрать сиквел или АР

2020-10-21 12:35 UTC, 7dr1v3 commented on lib/table_sync/receiving/handler.rb
> +          config.after_commit_on_update(**params.merge(results: results))
ок, убираю этот фильтр

2020-10-21 12:36 UTC, 7dr1v3 commented on lib/table_sync/receiving/model/active_record.rb
> +      sanitized_data = data.map { |attr| attr.select { |key, _value| target_keys.include?(key) } }
в хендлере после того как сформирован массив data на нем делает валидация, в том числе и таргет кейс проверяются

2020-10-21 12:38 UTC, 7dr1v3 commented on lib/table_sync.rb
> +    attr_reader :publishing_adapter
ну ок, это косается тольуо апи? это единственное место где указать?

2020-10-21 12:40 UTC, 7dr1v3 commented on lib/table_sync/receiving/model/active_record.rb
> +      sanitized_data.each.with_index do |row, index|
это ни на что не влияет

2020-10-21 12:40 UTC, 7dr1v3 commented on lib/table_sync/utils/interface_checker.rb
> +    self
что бы можно было в чейне проверять несколько интерфейсов

2020-10-21 12:42 UTC, 7dr1v3 commented on lib/table_sync/utils/proc_keywords_resolver.rb
> +# ¯\_(ツ)_/¯
для остальных звездочки не нужно, а вот именно в этом конкретном случае нужно?

2020-10-21 12:44 UTC, 7dr1v3 commented on lib/table_sync/utils/proc_keywords_resolver.rb
> +      proc_for_wrap.call(**keywords.slice(*available_keywords), &block)
зачем заставлять людей писать во всех опциях определяемых как прок все эти звездочки?

2020-10-21 12:45 UTC, 7dr1v3 commented on docs/messages_protocol.md
> +
не в этот раз, просто по минимуму сделал что бы в будущем дописать иначе тут еще кучу всего можно переписыывать.

2020-10-21 12:46 UTC, 7dr1v3 commented on lib/table_sync/receiving/config.rb
> +      return true if events.nil?
на самом деле нельзя, нафиг не нужно, я просто забыл удалить этот иф

2020-10-21 12:47 UTC, 7dr1v3 commented on lib/table_sync/utils/interface_checker.rb
> +class TableSync::Utils::InterfaceChecker
ну вот ты же догадался зачем это нужно) нафига описывать какие то частные случаи применения?

2020-10-21 13:05 UTC, 7dr1v3 commented on lib/table_sync.rb
> +    attr_reader :publishing_adapter
стоп, так апи же не изменилось, паблишинг адаптер скорее приватный

2020-10-21 16:46 UTC, 0exp commented on lib/table_sync/utils/interface_checker.rb
> +class TableSync::Utils::InterfaceChecker
ну описание типа о другом совсем) но оке, обсудили в ММ, хотим в таком виде запушить

2020-10-21 16:49 UTC, 0exp commented on docs/messages_protocol.md
> +
окей :+1:

2020-10-21 16:50 UTC, 0exp commented on lib/table_sync/utils/proc_keywords_resolver.rb
> +      proc_for_wrap.call(**keywords.slice(*available_keywords), &block)
оке, мы как раз это и делали (звездочки рисовали)

2020-10-21 16:52 UTC, 0exp commented on lib/table_sync/utils/proc_keywords_resolver.rb
> +# ¯\_(ツ)_/¯
ну да, руби же. но мы ниже выяснили че к чему

2020-10-21 16:52 UTC, 0exp commented on lib/table_sync/utils/interface_checker.rb
> +    self
это я понимаю. просто я не увидел, что в чейне где-то используем это

2020-10-21 16:53 UTC, 0exp commented on lib/table_sync/utils/interface_checker.rb
> +    self
но оке, нормуль

2020-10-21 16:54 UTC, 0exp commented on lib/table_sync/receiving/model/active_record.rb
> +      sanitized_data.each.with_index do |row, index|
так это же все равно что написать map.flatten вместо flat_map

2020-10-21 16:55 UTC, 0exp commented on lib/table_sync/receiving/model/active_record.rb
> +      sanitized_data = data.map { |attr| attr.select { |key, _value| target_keys.include?(key) } }
ну тогда значит тут не будет всяких [{}, {}] :+1:

2020-10-21 17:02 UTC, 0exp commented on lib/table_sync/receiving/model/active_record.rb
> +      sanitized_data.each.with_index do |row, index|
помимо этого мы создаем один итератор, потом второй (в твоем варианте). flat_map создаст только один. на масс-синках-пересинках по памяти будем меньше кушать (там это существенное влияние для сайдкека. как минимум у нас в проекте)

2020-10-21 17:06 UTC, 0exp commented on lib/table_sync.rb
> +    attr_reader :publishing_adapter
наверно вообще ко всему новому, но чуствую, что это будет люто муторно 🤔

2020-10-21 18:57 UTC, 7dr1v3 commented on lib/table_sync/receiving/model/active_record.rb
> +      sanitized_data.each.with_index do |row, index|
ну ок

2020-10-21 19:02 UTC, 7dr1v3 commented on lib/table_sync.rb
> +    attr_reader :publishing_adapter
я бы вообще забил на это, потому что правильный путь это вынести модели и адаптеры в отдельные гемы, то есть если тейбл синк будет приводиться в адекватное состояние этот код исчезнет, именно по этому я не вижу смысла менять сейчас интерфейс `orm =  ...`

2020-10-22 11:08 UTC, 0exp approved these changes

2020-10-22 18:24 UTC, loadkpi commented on lib/table_sync.rb
> +      @orm = val
ну ок

2020-10-22 18:25 UTC, loadkpi commented on lib/table_sync.rb
> +    attr_reader :publishing_adapter
я все еще считаю, что надо, давайте в отдельном мр..

2020-10-22 18:26 UTC, loadkpi commented on lib/table_sync/receiving/model/active_record.rb
> +      sanitized_data = data.map { |attr| attr.select { |key, _value| target_keys.include?(key) } }
проверил, действительно не будет

2020-10-22 18:28 UTC, loadkpi approved these changes

2020-10-23 09:25 UTC, merged