Skip publish when object is new and event is destroy
umbrellio/table_sync pull request #62
Opened 2021-12-01 12:55 UTC by AS-AlStar

Added check when object is new and event is destroy. Example:
```
user = User.new.destroy!
# job isn't creating and message isn't sending to rabbit 
```

2021-12-01 12:58 UTC, nulldef commented on lib/table_sync/setup/active_record.rb
> +        return if (self.new_record? && self.destroyed?)
there is a special method for that – `#persisted?`

2021-12-01 13:21 UTC, nulldef approved these changes

2021-12-02 08:14 UTC, VegetableProphet requested changes

2021-12-02 08:14 UTC, VegetableProphet commented on spec/support/shared/setup.rb
> +        if test_class_name == "TestARUser"
Думаю, смешивать логику в одном тесте не стоит.
Тесты для разных ОРМ не зря на два файла разделены.

Или для каждого отдельно напиши, или как-то надо сделать, чтобы тут остались только одинаковые моменты.

2021-12-02 08:14 UTC, VegetableProphet commented on lib/table_sync/setup/active_record.rb
> +        next if new_record? && destroyed?
Может тут тоже поднимать ошибку?

Чтобы было поведение идентичное Сиквелу.
Ну и это же ненормально, когда пытаются удалить несуществующие записи.

И тогда с тестами проще будет, кстати.

2021-12-02 08:14 UTC, VegetableProphet commented on docs/publishing.md
> +Features of ActiveRecord:
Я бы как-нибудь так написал.

```
### Non persisted record destruction

Sometimes destroy event can happen for non persisted record. In this case we can expect the following:

For Sequel: 'Sequel::NoExistingObject' is raised. (This is default Sequel behaviour)
For Active Record: Publishing is skipped. (Или можно тоже ошибку рейзить, чтобы одинаково было.)

Example:
тут пример
```

2021-12-02 08:47 UTC, AS-AlStar commented on spec/support/shared/setup.rb
> +        if test_class_name == "TestARUser"
Разделил на два файла

2021-12-02 08:48 UTC, AS-AlStar commented on lib/table_sync/setup/active_record.rb
> +        next if new_record? && destroyed?
не, думаю рейзить не нужно. Это уже ломает первоначальное поведение AR

2021-12-02 08:48 UTC, AS-AlStar commented on docs/publishing.md
> +Features of ActiveRecord:
+

2021-12-02 08:59 UTC, VegetableProphet commented on spec/setup/sequel_spec.rb
> +    context "when user is persisted" do
Ну этот-то можно и общим оставить.
Он идентичный.

2021-12-02 08:59 UTC, VegetableProphet commented on lib/table_sync/setup/active_record.rb
> +        next if new_record? && destroyed?
Ну ок.

2021-12-02 09:40 UTC, AS-AlStar commented on spec/setup/sequel_spec.rb
> +    context "when user is persisted" do
перенес

2021-12-02 10:53 UTC, VegetableProphet approved these changes

2021-12-02 10:54 UTC, merged