Ability to specify name of model when publishing raw data
umbrellio/table_sync pull request #64
Opened 2022-01-18 16:04 UTC by AnotherRegularDude

# Changes

- Add `model_name` attribute to the `raw` publishing interface. So now you can specify model name other then object class name when using `raw` method.

2022-01-18 16:21 UTC, tycooon commented
О, классная фича, можно будет у нас костылёк убрать 👍

2022-01-18 16:23 UTC, tycooon commented on docs/publishing/publishers.md
>  - `object_class` - model
А для чего там вообще object_class тогда? На что оно влияет?

2022-01-18 16:30 UTC, AnotherRegularDude commented on docs/publishing/publishers.md
>  - `object_class` - model
Для нотификаций используется, чтобы вытащить всякие `table` и `schema`

2022-01-18 16:44 UTC, tycooon commented on docs/publishing/publishers.md
>  - `object_class` - model
Хм, ну вообще это как-то странно, если у нас все кастомное – то кажется это тоже должно быть кастомное просто)

2022-01-18 17:02 UTC, AnotherRegularDude commented on docs/publishing/publishers.md
>  - `object_class` - model
Мне тоже показалось, что как-то не очень, что в роу пуше что-то там константизируется внутри и нотификации шлются.
Но вдруг кто сейчас подписан на это, а я все сломаю)

2022-01-18 20:02 UTC, tycooon commented on docs/publishing/publishers.md
>  - `object_class` - model
В общем срочно нужны мейнтейнеры.

2022-01-19 15:02 UTC, AnotherRegularDude commented on docs/publishing/publishers.md
>  - `object_class` - model
Знать, бы кто, теперь ~смотрящие~ мейнтенеры тейбл сюнка

Я потерялся на 4 версии :feels_bad_man:

Мб, я рили просто выпилю нотификацию, выпилю новое поле `model_name` и оставлю `object_class`, таким образом, ничего не сломается при обновлении, а просто нотификашки перестанут слаться?)

2022-01-19 15:03 UTC, AnotherRegularDude commented on docs/publishing/publishers.md
>  - `object_class` - model
@VegetableProphet, призовись

2022-01-19 15:28 UTC, VegetableProphet commented on docs/publishing/publishers.md
>  - `object_class` - model
Ага, вижу. Отпишусь на выходных скорее всего. Там надо смотреть, вспоминать.

2022-01-22 10:25 UTC, VegetableProphet commented on docs/publishing/publishers.md
>  - `object_class` - model
Так, ну я глянул.

Нотификацию выпиливать не надо. По ней, например, в Графане следим за пересинками.

Насчёт кастомного имени.
Вообще идея Raw в том, чтобы оно как раз не зависело от наличия реального класса.
Как-то я с нотификацией это упустил.

Я бы сделал так. Ничего там не константизировать.
Сделать два параметра. 
Типа: notification_table, notification_schema.
Если они указаны, то вставлять их при нотификации.
Если нет, то сделать schema: raw_sync, а table: object_class.tableize.

Почему так? Потому что на самом деле там же может и не существовать таблицы, соответствующей отправляемым данным.
А так оно будет указывать, что синкает. При этом отделять raw синк от обычного. Всё чётенько.

Заодно можно сделать опцию не нотифаить вообще, если тебе это не нужно.
Типа notify: true по дефолту. И можно сделать false.

P.S.
Также, если надо побыстрее, можно просто сделать синкательный класс. Некоторый хак.
Допустим, у тебя есть какой-нибудь класс User.

```
class CustomSyncUser < User
end
```

И синкаешь его просто.

2022-01-22 19:12 UTC, VegetableProphet requested changes
Написал в комменте, чего хочу.

2022-01-23 16:43 UTC, AnotherRegularDude commented on docs/publishing/publishers.md
>  - `object_class` - model
Ага, я сначала костыль такой запилил, только просто константу создал: `CustomSyncUser = User`, но решил, что лучше ПР бахнуть

2022-01-23 16:48 UTC, AnotherRegularDude commented on docs/publishing/publishers.md
>  - `object_class` - model
Я еще добавлю тогда глобальный конфиг, который включает, отключает нотификации, шоб везде не нуно было перекидывать `notify: false`

2022-01-23 16:49 UTC, AnotherRegularDude commented on docs/publishing/publishers.md
>  - `object_class` - model
> schema: raw_sync, а table: object_class.tableize.

Я б с ошибкой падал, если честно)

А то так мы играем в неочевидную угадайку для того, чтоб не падало

2022-01-23 20:23 UTC, VegetableProphet commented on docs/publishing/publishers.md
>  - `object_class` - model
1) А там щас уже сделано так, что если нотифиер не указан, то оно не будет нотифаить.
Хотя это немножко неочивидно, кажется. Можно на очевидное notify: true | false переделать.
И кидать ошибку, если нотифиер не указан.

2) Если падать с ошибкой, то придётся каждый раз проставлять при использовании публишера. Это очень неудобно. Просто в доке написали бы, что он там такое проставляет. Вроде норм размен.

3) Или тогда какие-нибудь коллабл сделать для проставления. Как для роутинг_ки и метадаты.
И требовать, чтобы он был заполнен, если нотификации включены.

Можно тогда сделать так:
- сделать notify: true | false вместо просто не отправления при отсутствии нотифиера
- сделать коллаблс для схемы и таблицы в нотификейшене
- сделать notification_schema, notification_table для оверрайда коллабл
- просто скипать, если нотифай: фолс

2022-01-24 09:54 UTC, AnotherRegularDude commented on docs/publishing/publishers.md
>  - `object_class` - model
Окей. давай я все это тут запилю :+1:

2022-02-07 05:58 UTC, 0exp approved these changes

2022-04-18 07:55 UTC, VegetableProphet commented on lib/table_sync/publishing/params/raw.rb
> +    attribute :exchange_name, default: -> { TableSync.exchange_name }
Это всё повторяет то, что в Base. Тут из нового только model_name и alias. Две строчки.

2022-04-18 07:55 UTC, VegetableProphet commented on lib/table_sync.rb
> +    def notifier=(value)
Я может не увидел, но было бы неплохо описать поведение нотифай и нотифиер в доке (с примерами, и какое поведение ожидать при их разных значениях).
И в ченджлоге.

2022-11-09 13:43 UTC, AnotherRegularDude commented on lib/table_sync/publishing/params/raw.rb
> +    attribute :exchange_name, default: -> { TableSync.exchange_name }
А шо там повторяет в `Base`?

В бейзе везде рейзится нот имплементед

2022-11-09 13:46 UTC, AnotherRegularDude commented on docs/publishing/publishers.md
>  - `object_class` - model
Тут конверсейшен закрываем?

2022-11-10 09:29 UTC, VegetableProphet requested changes

2022-11-10 09:29 UTC, VegetableProphet commented on lib/table_sync/instrument.rb
> +  def required_args
А зачем вот это всё? Почему не просто константа?
Выглядит как неизменный набор.

2022-11-10 09:29 UTC, VegetableProphet commented on lib/table_sync/publishing/params/raw.rb
> +    attribute :exchange_name, default: -> { TableSync.exchange_name }
Фу, не в Base, а в Batch. от которого оно наследовало изначально.

2022-11-10 09:41 UTC, AnotherRegularDude commented on lib/table_sync/instrument.rb
> +  def required_args
Не люблю заводить константы ради того, чтоб их в одном месте использовать у того же класса.

При этом тут еще `extend self`, так шо есть возможность спрятать в приватку

2022-11-10 10:03 UTC, VegetableProphet commented on lib/table_sync/instrument.rb
> +  def required_args
Немного странно, честно говоря. Не понимаю, чем такое динамическое определение в модуле лучше константы.
Наоборот приходится думать о том, зачем так сделано. 

Но ок.
Не принципиально.

2022-11-24 21:52 UTC, AnotherRegularDude commented
@VegetableProphet, го дропнем руби 2.5 хотя бы (я б, канеш, и 2.6 дропнул), у них уже еол

Я прост фиг знает, как убрать required с джобки по 2.5: у меня нет доступа к настройкам

2022-11-24 22:04 UTC, 0exp commented
@AnotherRegularDude а они просто в CI-матрице в CI.yml лежат
давайте 2.5 дропнем, уже абсолютно устарел

2022-11-24 22:05 UTC, 0exp commented
2.6 я бы в январе дропнул

2022-11-24 22:07 UTC, 0exp approved these changes

2022-11-28 08:13 UTC, AnotherRegularDude commented
> @AnotherRegularDude а они просто в CI-матрице в CI.yml лежат давайте 2.5 дропнем, уже абсолютно устарел

А я дропнул

Но вон 2.5 `Required ` пишет

Видимо, это в настройках правится

2022-12-06 13:01 UTC, VegetableProphet approved these changes

2022-12-06 13:52 UTC, AnotherRegularDude commented on CHANGELOG.md
> +## [6.1.0] - 2022-01-18
Косяк)

Сейчас поправлю

Кстати, 

2.5 Expected — Waiting for status to be reported 

Как ето убрать? Как будто нужно в настройки проекта идти

2022-12-06 21:49 UTC, AnotherRegularDude commented on CHANGELOG.md
> +## [6.1.0] - 2022-01-18
В самих файлах репы я ничего не нашел

@tycooon, @0exp, памахити пожожда

Етот ПР должен вмержится :pepe-cat-cry:

2022-12-07 11:39 UTC, 0exp commented on CHANGELOG.md
> +## [6.1.0] - 2022-01-18
попробую сегодня вечерочком чекнуть CI

2023-02-16 11:36 UTC, merged